NORMALIZATION_CONSTANT = 0.5 #avoids negative numbers
MAX_INPUT_LAYER_SIZE = 30
MAX_HIDDEN_LAYER_SIZE = 50
MAX_OUTPUT_LAYER_SIZE = 7
MSE = 0.01
MAX_ITERATIONS = 1000
TRAINING_RATIO = 0.8
#used for tests which return numerical values
ACC_ERROR = 0.001