# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5641843f33b832e333877c20c12c7a4830be239e70c5a06a35e1872a5c84104f25ecd2bd0391abfaf9c7372f3aa5ed55ad692c3173b5d5ba36091c915cc9fce

test:
  secret_key_base: 22e015a464709868b7672ba6ecc5f1f18efb4aa08a1a54f0a53c7421f17d7eb709a477e49b70844fb719c53e653fede7e218957578e5c534e56ca0a176025c70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
